GRANT CONNECT ON DATABASE neondb TO blackwall_app;

GRANT USAGE ON SCHEMA public TO blackwall_app;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO blackwall_app;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO blackwall_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO blackwall_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO blackwall_app;