import type { Metadata } from 'next'
import './globals.css'
import { Roboto_Mono } from 'next/font/google'
import { cn } from '@/lib/utils'
import { CartOverlay } from '@/components/layout'
import { SessionProvider } from 'next-auth/react'
import { Navbar } from '@/components/layout/navbar'
import { AuthWatcher, CookieModal } from '@/components/shared'
import { Footer } from '@/components/layout/footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const robotoMono = Roboto_Mono({
  subsets: ['latin'],
  variable: '--font-mono',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn(robotoMono.variable, 'antialiased')}>
        <SessionProvider refetchInterval={30} refetchOnWindowFocus={true}>
          <Navbar />
          <AuthWatcher />
          <CartOverlay />
          <main className="px-4 xl:px-20">{children}</main>
          <Footer />
          <CookieModal />
        </SessionProvider>
      </body>
    </html>
  )
}
