import type { Metadata } from 'next'
import './globals.css'
import { Navbar } from '@/components/layout/navbar'
import { Roboto_Mono } from 'next/font/google'
import { cn } from '@/lib/utils'
import { Footer } from '@/components/layout/footer'
import { CartOverlay } from '@/components/layout'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const robotoMono = Roboto_Mono({
  subsets: ['latin'],
  variable: '--font-mono',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn(robotoMono.variable, 'antialiased')}>
        <Navbar />
        <CartOverlay />
        <main className="px-4 xl:px-20">{children}</main>
        <Footer />
      </body>
    </html>
  )
}
